# Generated by Django 3.2.5 on 2021-08-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='read_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
