# Generated by Django 3.2.6 on 2021-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_books_read_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='read_date',
        ),
    ]
